# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketLeftOver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketLeftOver
  pod 'Alamofire', '~> 4.7'

end
